version: '3.8'

services:
  app:
    build:
      context: . # Path to the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map port 5000 on the host to port 5000 in the container
    volumes:
      - .:/app # Bind the current directory to the /app directory in the container
      - /app/node_modules # Prevent overwriting node_modules in the container
    environment:
      - NODE_ENV=development # Set environment variables
    command: npm start # Run the application
